entrypoints:
- name: http
  address: ":8080"
- name: https
  address: ":4433"
  protocol: https
  tls:
    certfile: example/test.crt
    keyfile: example/test.key
applications:
- port: 9000
  protocol: http
  domain: example.com
logPath: example/test.log    