on: [push]
name: Build & Test
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: build
      uses: cedrickring/golang-action@1.3.0
      env:
        GO111MODULE: "on"